version: '3'

services:
  medusa:
    command: bash -c "npx medusa migrations run && npm start"

    build: .
    environment:
      - DATABASE_URL=postgres://medusa_user:12345@db:5432/medusa_db
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=supersecret
      - COOKIE_SECRET=supersecret
    ports:
      - "9000:9000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=medusa_user
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=medusa_db
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data:
