name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main # Trigger the workflow on push to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
         run: |
                docker build -t medusa-backend:latest . /workspaces/PearlThoughts-Medusa/Task-7

      - name: Tag Docker image
        run: |
          REPOSITORY_URI=992382465189.dkr.ecr.us-east-1.amazonaws.com/medusa-backend
          docker tag medusa-backend:latest $992382465189.dkr.ecr.us-east-1.amazonaws.com/medusa-backend:latest

      - name: Push Docker image to ECR
        run: |
          REPOSITORY_URI=992382465189.dkr.ecr.us-east-1.amazonaws.com/medusa-backend
          docker push $992382465189.dkr.ecr.us-east-1.amazonaws.com/medusa-backend:latest
