# Use the official Node.js image
FROM node:16-alpine

# Set the working directory inside the container
WORKDIR /app

# Install bash and PostgreSQL client
RUN apk add --no-cache bash libpq

# Install Medusa CLI globally
RUN npm install -g @medusajs/medusa-cli

# Copy the package.json and package-lock.json to the working directory
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of your application code to the container
COPY . .

# Expose the necessary port
EXPOSE 9000

# Start the Medusa server
CMD ["medusa", "start"]
