name: Medusa EC2 Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

      - name: SSH into EC2 and Deploy Medusa
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} "
            cd /home/ubuntu/PearlThoughts-Medusa/Task-4/my-medusa-store && \
            git pull origin main && \
            sudo apt update && \
            node -v && \
            npm -v && \
            sudo service postgresql start && \
            npx medusa migrations run && \
            nohup medusa develop > medusa.log 2>&1 &
          "
