name: Medusa EC2 Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

      - name: SSH into EC2 and Deploy Medusa
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@<EC2_PUBLIC_IP> << 'EOF'
            cd /home/ubuntu/PearlThoughts-Medusa/Task-4/my-medusa-store

            # Pull the latest changes from GitHub
            git pull origin main

            # Update system and check for Node.js & npm
            sudo apt update
            node -v
            npm -v

            # Start PostgreSQL and ensure the database is running
            sudo service postgresql start

            # Run Medusa migrations
            npx medusa migrations run

            # Start Medusa in development mode
            nohup medusa develop > medusa.log 2>&1 &
          EOF
