name: Deploy to EC2  

on:  
  push:   
    branches:  
      - main  

jobs:  
  deploy:  
    runs-on: ubuntu-latest  

    steps:  
      - name: Checkout repository  
        uses: actions/checkout@v2  

      - name: Setup SSH key  
        uses: webfactory/ssh-agent@v0.5.4  
        with:  
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}  

      - name: Deploy to EC2  
        run: |  
          ssh -o "StrictHostKeyChecking=no" ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'  
            cd /home/ubuntu/PearlThoughts-Medusa/Task-4/my-medusa-store || exit  
            cd /home/ubuntu/PearlThoughts-Medusa/Task-4/my-medusa-store || exit  
            git pull origin main  
            npm install -g pm2  
            npx medusa migrations run  
            pm2 restart medusa || pm2 start npm --name "medusa" -- start  
          EOF
