name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_KEY_PAIR }}

      - name: Deploy to EC2
        run: |
          ssh ubuntu@${{ secrets.EC2_PUBLIC_IP }} "mkdir -p ~/my-app"
          scp -r . ubuntu@${{ secrets.EC2_PUBLIC_IP }}:~/my-app

      - name: Install dependencies
        run: |
          ssh ubuntu@${{ secrets.EC2_PUBLIC_IP }} "cd ~/my-app && npm install"

      - name: Start application
        run: |
          ssh ubuntu@${{ secrets.EC2_PUBLIC_IP }} "cd ~/my-app && npm start"
