name: Deploy to EC2  

on:  
  push:  
    branches:  
      - main  

jobs:  
  deploy:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v2  

      - name: Setup SSH  
        uses: webfactory/ssh-agent@v0.5.4  
        with:  
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}  

      - name: Connect to EC2 and Deploy  
        run: |  
          ssh -o "StrictHostKeyChecking=no" ubuntu@${{ secrets.EC2_PUBLIC_KEY }} << 'EOF'  
            cd /correct/path/to/your/app || exit  
            
            # Add git safe.directory exception  
            git config --global --add safe.directory /home/ubuntu/PearlThoughts-Medusa  
            
            # Change ownership (if needed)  
            sudo chown -R ubuntu:ubuntu /home/ubuntu/PearlThoughts-Medusa  
            
            # Install PM2 if not present  
            npm install -g pm2 || exit  
            
            # Pull the latest changes  
            git pull origin main  
            
            # Install dependencies  
            npm install || exit  
            
            # Run migrations  
            npx medusa migrations run || exit  
            
            # Restart or start the app using PM2  
            pm2 restart medusa || pm2 start npm --name "medusa" -- start  
          EOF
