name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_KEY_PAIR }}

      - name: Deploy to EC2
        uses: actions/scp-action@v3
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          source: "."
          target: "~/my-app"

      - name: Install dependencies
        uses: actions/ssh-action@v3
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          command: |
            cd ~/my-app
            npm install

      - name: Start application
        uses: actions/ssh-action@v3
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          command: |
            cd ~/my-app
            npm start
