name: Deploy to EC2  

on:  
  push:   
    branches:  
      - main  

jobs:  
  deploy:  
    runs-on: ubuntu-latest  

    steps:  
      - name: Checkout repository  
        uses: actions/checkout@v2  

      - name: Setup SSH key  
        uses: webfactory/ssh-agent@v0.5.4  
        with:  
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}  

      - name: Deploy to EC2  
        run: |  
          ssh -o "StrictHostKeyChecking=no" ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'  
            cd /home/ubuntu/PearlThoughts-Medusa/Task-4/my-medusa-store || exit  
            cd /home/ubuntu/PearlThoughts-Medusa/Task-4/my-medusa-store || exit  
            git config --global --add safe.directory /home/ubuntu/PearlThoughts-Medusa
            sudo chown -R ubuntu:ubuntu /home/ubuntu/PearlThoughts-Medusa
# Check if npm prefix directory exists  
            if [ ! -d "$HOME/.npm-global" ]; then  
              mkdir "$HOME/.npm-global"  
              npm config set prefix "$HOME/.npm-global"  
              echo 'export PATH=$HOME/.npm-global/bin:$PATH' >> ~/.bashrc  
              source ~/.bashrc  
            fi  
            
            # Install PM2 globally without sudo  
            npm install -g pm2 || sudo npm install -g pm2  
            
            # Pull the latest changes  
            git pull origin main  
            
            # Install dependencies  
            npm install || exit  
            
            # Run migrations  
            npx medusa migrations run || exit  
            
            # Restart or start the app using PM2  
            pm2 restart medusa || pm2 start npm --name "medusa" -- start  
          EOF  
            
