name: Medusa Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd medusa
          npm install

      - name: Deploy to EC2
        uses: actions/scp-action@v1.0.5
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: "."
          target: ~/medusa

     
      - name: Run Medusa migrations and start development server
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          command: |
            cd ~/medusa
            npx medusa migrations run
            medusa develop



